changelog:
  exclude:
    labels:
      - skip-changelog
      - duplicate
  categories:
    - title: Breaking Changes
      labels:
        - breaking
    - title: Enhancements
      labels:
        - enhancement
    - title: Bug Fixes
      labels:
        - bug
    - title: Documentation
      labels:
        - documentation
    - title: Dependencies
      labels:
        - dependencies
    - title: Maintenance
      labels:
        - maintenance
    - title: Other Changes
      labels:
        - "*"
